(define (domain pick-and-place)
  (:requirements :strips :equality)
  (:predicates
    (Stackable ?o ?r)
    (Sink ?o)
    (Stove ?s)
    (Floor ?f)
    (Movable ?o)
    (Region ?s)

    (Pose ?o ?p)
    (ValidGrasp ?o ?p ?q)
    (Grasp ?o ?g)
    (Kin ?o ?p1 ?p2 ?g ?q2 ?t)
    (FreeMotion ?q1 ?t ?q2)
    (HoldingMotion ?q1 ?t ?q2 ?o ?p1 ?p2 ?g)
    (Supported ?o ?p ?r)
    (Traj ?t)

    (TrajCollision ?t ?o2 ?p2)
    (CFreePosePose ?o ?p ?o2 ?p2)
    (CFreeApproachPose ?o ?p ?g ?o2 ?p2)
    (CFreeTrajPose ?t ?o2 ?p2)

    (AtPose ?o ?p)
    (AtGrasp ?o ?g)
    (AtGraspPose ?o ?p ?q)
    (HandEmpty)
    (AtConf ?q)
    (CanMove)
    (Cleaned ?o)
    (Cooked ?o)

    (On ?o ?r)
    (Holding ?o)

    (UnsafePose ?o ?p)
    (UnsafeApproach ?o ?p ?g)
    (UnsafeTraj ?t)

    (PickInfeasible ?o ?r ?f ?p)
    (PickFeasible ?o ?r ?f ?p ?o1 ?p1)
    (PickRegion ?o ?s)

    (PlaceInfeasible ?o ?s ?r)
    (PlaceFeasible ?o ?s ?r ?o1 ?p1)

    (MoveInfeasible ?o ?p1 ?p2 ?q1 ?q2)
    (MoveFeasible ?o ?p1 ?p2 ?q1 ?q2 ?o1 ?p1)

  )

  (:action move_free
    :parameters (?q1 ?q2 ?t)
    :precondition (and (FreeMotion ?q1 ?t ?q2)
                       (AtConf ?q1) (HandEmpty) (CanMove)
                       ;(not (UnsafeTraj ?t))
                  )
    :effect (and (AtConf ?q2)
                 (not (AtConf ?q1)) (not (CanMove)))
  )

  (:action move_holding
    :parameters (?q1 ?q2 ?o ?p1 ?p2 ?g ?t)
    :precondition (and (not (MoveInfeasible ?o ?p1 ?p2 ?q1 ?q2))
                       (ValidGrasp ?o ?p1 ?q1) (ValidGrasp ?o ?p2 ?q2)
                       (HoldingMotion ?q1 ?t ?q2 ?o ?p1 ?p2 ?g)
                       (AtConf ?q1) (AtGrasp ?o ?g) (CanMove)
                       ;(AtPose ?o ?p1)
                       (AtGraspPose ?o ?p1 ?q1)
                       ;(not (UnsafeTraj ?t))
                  )
    :effect (and (AtConf ?q2)
                 (not (AtConf ?q1)) (not (CanMove))
                 ;(not (AtPose ?o ?p1))
                 ;(AtPose ?o ?p2)
                 (not (AtGraspPose ?o ?p1 ?q1))
                 (AtGraspPose ?o ?p2 ?q2)
                 )
  )

  (:action pick
    :parameters (?o ?r ?f ?p1 ?p2 ?g ?q ?t)
    :precondition (and (not (PickInfeasible ?o ?r ?f ?p1))
                       (Kin ?o ?p1 ?p2 ?g ?q ?t)
                       (On ?o ?r) (Region ?r) (Floor ?f)
                       (AtPose ?o ?p1) (HandEmpty) (AtConf ?q) (Movable ?o)
                       (not (UnsafeApproach ?o ?p ?g))
                       (not (UnsafeTraj ?t))
                  )
    :effect (and (AtGrasp ?o ?g) (CanMove)
                 (not (AtPose ?o ?p1)) (not (HandEmpty))
                 ;(AtPose ?o ?p2)
                 (AtGraspPose ?o ?p2 ?q)
                 (PickRegion ?o ?r)
                 )
  )

  (:action place
    :parameters (?o ?s ?r ?p1 ?p2 ?g ?q ?t)
    :precondition (and (not (PlaceInfeasible ?o ?s ?r))
                       (PickRegion ?o ?s)
                       (Stackable ?o ?r) (Supported ?o ?p1 ?r)
                       (Kin ?o ?p1 ?p2 ?g ?q ?t)
                       (AtGrasp ?o ?g) (AtConf ?q)
                       ;(AtPose ?o ?p2)
                       (AtGraspPose ?o ?p2 ?q)
                       (not (UnsafePose ?o ?p))
                       (not (UnsafeApproach ?o ?p ?g))
                       (not (UnsafeTraj ?t))
                  )
    :effect (and (AtPose ?o ?p1) (HandEmpty) (CanMove)
                 (not (AtGrasp ?o ?g))
                 ;(not (AtPose ?o ?p2))
                 (not (AtGraspPose ?o ?p2 ?q))
                 (not (PickRegion ?o ?s))
                 )
  )

  (:action clean
    :parameters (?o ?r)
    :precondition (and (Stackable ?o ?r) (Sink ?r)
                       (On ?o ?r))
    :effect (Cleaned ?o)
  )
  (:action cook
    :parameters (?o ?r)
    :precondition (and (Stackable ?o ?r) (Stove ?r)
                       (On ?o ?r) (Cleaned ?o))
    :effect (and (Cooked ?o)
                 (not (Cleaned ?o)))
  )

  (:derived (On ?o ?r)
    (exists (?p) (and (Supported ?o ?p ?r)
                      (AtPose ?o ?p)))
  )
  (:derived (Holding ?o)
    (exists (?g) (and (Grasp ?o ?g)
                      (AtGrasp ?o ?g)))
  )

  (:derived (UnsafePose ?o ?p)
    (exists (?o2 ?p2) (and (Pose ?o ?p) (Pose ?o2 ?p2) (not (= ?o ?o2))
                           (not (CFreePosePose ?o ?p ?o2 ?p2))
                           (AtPose ?o2 ?p2)))
  )
  (:derived (UnsafeApproach ?o ?p ?g)
    (exists (?o2 ?p2) (and (Pose ?o ?p) (Grasp ?o ?g) (Pose ?o2 ?p2) (not (= ?o ?o2))
                           (not (CFreeApproachPose ?o ?p ?g ?o2 ?p2))
                           (AtPose ?o2 ?p2)))
  )
  (:derived (UnsafeTraj ?t)
    (exists (?o2 ?p2) (and (Traj ?t) (Pose ?o2 ?p2)
                           (not (CFreeTrajPose ?t ?o2 ?p2))
                           ; (TrajCollision ?t ?o2 ?p2)
                           (AtPose ?o2 ?p2)))
  )
  (:derived (PickInfeasible ?o ?r ?f ?p)
    (exists (?o1 ?p1) (and (AtPose ?o ?p) (AtPose ?o1 ?p1) (Pose ?o ?p) (Pose ?o1 ?p1)
                           (Movable ?o1) (not (= ?o ?o1))
                           (Floor ?f) (Supported ?o ?p ?r) (Region ?r) 
                           (not (PickFeasible ?o ?r ?f ?p ?o1 ?p1))
                      )
    )
  )
  (:derived (PlaceInfeasible ?o ?s ?r)
    (exists (?o1 ?p1) (and (AtPose ?o1 ?p1) (Pose ?o1 ?p1)
                           (Region ?s) (PickRegion ?o ?s)
                           (Stackable ?o ?r)
                           (Movable ?o1) (not (= ?o ?o1))
                           (not (PlaceFeasible ?o ?s ?r ?o1 ?p1))
                      )
    )
  )
  (:derived (MoveInfeasible ?o1 ?p11 ?p12 ?q11 ?q12)
    (exists (?o2 ?p21) (and (AtGraspPose ?o1 ?p11 ?q11)
                            (ValidGrasp ?o1 ?p11 ?q11) (ValidGrasp ?o1 ?p12 ?q12)
                            (AtPose ?o1 ?p1) (Pose ?o1 ?p1) 
                            (Movable ?o1) (not (= ?o1 ?o2))
                            (not (MoveFeasible ?o ?p1 ?p2 ?q1 ?q2 ?o1 ?p1))
                       )
    )
  )
)
